#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  motorA,          gripMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          wristMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Extend_Arm,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStart(); // Wait for the beginning of autonomous phase.


	int _dirAC = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;
	int maxSig = 100; // the max signal strength from the seeker.
	int val = 0; // the translated directional value.
	// we are going to set DSP mode to 1200 Hz.
	tHTIRS2DSPMode _mode = DSP_1200;
	// attempt to set to DSP mode.
	if (HTIRS2setDSPMode(HTIRS2, _mode) == 0)
	{
		// unsuccessful at setting the mode.
		// display error message.
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 2.");
		// make a noise to get their attention.
		PlaySound(soundBeepBeep);
		// wait so user can read message, then leave main task.
		wait10Msec(300);
		return;
	}
	eraseDisplay();
	// loop continuously and read from the sensor.


	//code to lift arm, move forward - for use after ir tracking is debugged - from Dave

	//while (nMotorEncoder[mtr_S1_C3_2]<=50)		//while arm encode is less than or equal to 50 (not sure of value)
	//{
	//	motor[Extend_Arm]=25;										// lift arm at 25%
	//}

	//servo[servo6] = 80;								// start moving wrist down

	//while (nMotorEncoder[mtr_S1_C3_2]<=75)		//while arm encode is less than or equal to 75 (not sure of value)
	//{
		//motor[Extend_Arm]=25;										// lift arm at 25%
	//}

	//servo[servo6] = 10;								// move wrist down all of the way


	//motor[mtr_S1_C1_1] = 50;			// drive forwards 1 sec, then stop
	//motor[mtr_S1_C1_2] = 50;
	//wait1Msec(1000);
	//motor[mtr_S1_C1_1] = 0;
	//motor[mtr_S1_C1_2] = 0;

	while(maxSig>0)														// while not to close to beacon (not sure of value)
	{
		// read the current modulated signal direction
		_dirAC = HTIRS2readACDir(HTIRS2);

		if (_dirAC < 0)

		{
			// error! - write to debug stream and then break.
			writeDebugStreamLine("Read dir ERROR!");
			//break;
		}
		// Get the AC signal strength values.
		if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
		{
			// error! - write to debug stream and then break.
			writeDebugStreamLine("Read sig ERROR!");
			//break;
		}
		else
		{
			// find the max signal strength of all detectors.
			maxSig = (acS1 > acS2) ? acS1 : acS2;
			maxSig = (maxSig > acS3) ? maxSig : acS3;
			maxSig = (maxSig > acS4) ? maxSig : acS4;
			maxSig = (maxSig > acS5) ? maxSig : acS5;
		}
		// display info
		nxtDisplayCenteredBigTextLine(1, "Dir=%d", _dirAC);
		nxtDisplayCenteredBigTextLine(4, "Sig=%d", maxSig);
		// figure out which direction to go...
		// a value of zero means the signal is not found.
		// 1 corresponds to the far left (approx. 8 o'clock position).
		// 5 corresponds to straight ahead.
		// 9 corresponds to far right.
		// first translate directional index so 0 is straight ahead.

		val = _dirAC - 5;

		// calculate left and right motor speeds.


		motor[mtr_S1_C1_1] = 50 + 30 * val;			// drive towards beacon
		motor[mtr_S1_C1_2] = 50 - 30 * val;

		// wait a little before resuming.
		wait10Msec(2);
	}


	//more code for use after ir tracking works - from Dave
	//while (nMotorEncoder[mtr_S1_C3_2]>=50)		//while arm encode is less than or equal to 50 (not sure of value)
	//{
		//motor[Extend_Arm]=-25;										// lift arm at 25%
  //}

}
