#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     HTIRS2,  sensorI2CCustom)
#pragma config(Motor,  motorA,          gripMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          wristMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Extend_Arm,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers/hitechnic-irseeker-v2.h"


task main()
{
  	motor[mtr_S1_C1_1]=20;			// drive towards beacon
		motor[mtr_S1_C1_2]=20;
		wait10Msec(300);
//  waitForStart(); // Wait for the beginning of autonomous phase. Tournament only


	int _dirAC = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;
	int maxSig = 100; // the max signal strength from the seeker.
	int val = 0; // the translated directional value.
	// we are going to set DSP mode to 1200 Hz.
	tHTIRS2DSPMode _mode = DSP_1200;
	// attempt to set to DSP mode.
	if (HTIRS2setDSPMode(HTIRS2, _mode) == 0)
	{
		// unsuccessful at setting the mode.
		// display error message.
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "ERROR!");
		nxtDisplayCenteredTextLine(2, "Init failed!");
		nxtDisplayCenteredTextLine(3, "Connect sensor");
		nxtDisplayCenteredTextLine(4, "to Port 2.");
		// make a noise to get their attention.
		PlaySound(soundBeepBeep);
		// wait so user can read message, then leave main task.
		wait10Msec(300);
		return;
	}
	eraseDisplay();


	while(maxSig>0)														// while not to close to beacon (not sure of value)
	{
		// read the current modulated signal direction
		_dirAC = HTIRS2readACDir(HTIRS2);

		if (_dirAC < 0)

		{
			// error! - write to debug stream and then break.
			writeDebugStreamLine("Read dir ERROR!");
			//break;
		}
		// Get the AC signal strength values.
		if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
		{
			// error! - write to debug stream and then break.
			writeDebugStreamLine("Read sig ERROR!");
			//break;
		}
		else
		{
			// find the max signal strength of all detectors.
			maxSig = (acS1 > acS2) ? acS1 : acS2;
			maxSig = (maxSig > acS3) ? maxSig : acS3;
			maxSig = (maxSig > acS4) ? maxSig : acS4;
			maxSig = (maxSig > acS5) ? maxSig : acS5;
		}
		// display info
		nxtDisplayCenteredBigTextLine(1, "Dir=%d", _dirAC);
		nxtDisplayCenteredBigTextLine(4, "Sig=%d", maxSig);
		// figure out which direction to go...
		// a value of zero means the signal is not found.
		// 1 corresponds to the far left (approx. 8 o'clock position).
		// 5 corresponds to straight ahead.
		// 9 corresponds to far right.
		// first translate directional index so 0 is straight ahead.

		val = _dirAC - 5;

		// calculate left and right motor speeds.
		motor[mtr_S1_C1_1]=80;			// drive towards beacon
		motor[mtr_S1_C1_2]=20;

		wait10Msec(20);
	}


	//more code for use after ir tracking works - from Dave
	//while (nMotorEncoder[mtr_S1_C3_2]>=50)		//while arm encode is less than or equal to 50 (not sure of value)
	//{
		//motor[Extend_Arm]=-25;										// lift arm at 25%
  //}

}
