#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     IRSeeker,       sensorI2CMuxController)
#pragma config(Motor,  motorA,          gripMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          wristMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Extend_Arm,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

	int threshold = 5;             /* Int 'threshold' will allow us to ignore low       */
  int a = ServoValue[servo[srvo_S1_C2_6]];
	servoChangeRate[srvo_S1_C2_5] = 4;

  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);
    if(abs(joystick.joy1_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[mtr_S1_C1_1] = joystick.joy1_y2-75;         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[mtr_S1_C1_1] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy1_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[mtr_S1_C1_2] = joystick.joy1_y1-75;         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                   // Else if the readings are within the threshold:
    {
    motor[mtr_S1_C1_2] = 0;      																																																																																																															                  // Motor C is stopped with a power level of 0.
    }





		if(joy1Btn(6))
		{
			{
        servo[srvo_S1_C2_6] = 175;
			}
		}
		else if(joy1Btn(5))
		{
      {
        servo[srvo_S1_C2_6] = 10 ;
			}
		}
		else if(joy1Btn(4))
		{
			{
				servo[srvo_S1_C2_6] = 80;
			}
		}
		if(joy1Btn(7)){motor[ramp]=10;}
		else if(joy1Btn(8)){motor[ramp]=-20;}
		else{motor[ramp]=0;}

		if(joy1Btn(1)){motor[Extend_Arm]=25;}
		else if(joy1Btn(2)){motor[Extend_Arm]=-15;}
		else
		{
			motor[Extend_Arm]=0;
		}
	}// Infinite loop:
}	 //END MAIN
