#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     rightSonar,     sensorSONAR)
#pragma config(Sensor, S2,     leftSonar,      sensorSONAR)
#pragma config(Sensor, S3,     IReader,        sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          DumpA,         tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          DumpB,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Scoop,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     backRight,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     frontRight,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_2,     frontLeft,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "hitechnic-irseeker-v2.h"

#define blueX     0x01
#define greenA    0x02
#define redB      0x04
#define yellowY   0x08
#define lBumper   0x10
#define rBumper   0x20
#define lTrigger  0x40
#define rTrigger		0x80
#define backButton  0x100
#define startButton 0x200

const bool bLogarithmicScale = true;
const int driveTrsh = 20;
const int slow = 20;
const int fast = 60;
bool startPressed = true;
bool backPressed  = false;
int kMaximumPowerLevel;  // Adjust to set max power level to be used.
int distance_in_cm = 15;
int autoSpeed = 30;

int scaleJoystick(int &nJoy1, int nMaxValue = kMaximumPowerLevel)
{
	// Joystick values range from -128 to +127.
	// Speed/power settings for NXT motors range from -100 to +100
	//
	// The physical range of motion of a joystick is quite small and it is sometimes
	// hard to control slow speeds. So another capability of this program to apply
	// a "logarithmic" scale to the joystick settings.
	static const int nLogScale[17] = {0,5,9,10,12,15,18,24,30,36,43,50,60,72,85,100,100};
	int nScaled;

	nScaled = nJoy1;
	nScaled = nJoy1;
	if (bLogarithmicScale)
	{
	  nScaled /= 8;
	  if (nScaled >= 0)
	    nScaled = nLogScale[nScaled];
	  else
	    nScaled = - nLogScale[ - nScaled];
  }
	nScaled *= nMaxValue;
	nScaled /= 100;
  return nScaled;
}



task main()
{
	//Set up Initial Params
	kMaximumPowerLevel = slow;

	//Set up IR Seeker
	int _dirDC = 0;
  int _dirAC = 0;
	int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;

	// the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;


	nMotorEncoder[Scoop] = 0;                // Reset the Motor Encoder @ floor Level.
	nMotorEncoderTarget[Scoop] = -15;        // Set the  target for Motor Encoder.
	motor[Scoop] = -10;

	while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);

    /**
    * Buttons to control Scoop & Dump
    */

    if (joystick.joy1_Buttons & blueX)
    {
			motor[Scoop] = -40;
    }
    else if (joystick.joy1_Buttons & greenA)
    {
			motor[Scoop] = 20;
    }
    else if (joystick.joy1_Buttons & yellowY)
    {
			motor[DumpA] = -15;
			motor[DumpB] = -15;
    }
    else if (joystick.joy1_Buttons & redB)
    {
			motor[DumpA] = 15;
			motor[DumpB] = 15;
    }
    else{
    	motor[Scoop] = 0;
    	motor[DumpA] = 0;
			motor[DumpB] = 0;
    }


    /**
    * Button to switch IR modes (overriding follow)
    */
/*
   	if(joystick.joy1_Buttons & backButton){
   		if(backPressed){
   			backPressed = false;
				PlaySound(soundFastUpwardTones);
			}
			else{
				backPressed = true;
				PlaySound(soundDownwardTonesq);
			}
			wait1Msec(200);
			ClearSounds();
		}

    if(backPressed){
    	// Read the current non modulated signal direction
      _dirDC = HTIRS2readDCDir(HTIRS2);
      if (_dirDC < 0)
        break; // I2C read error occurred



    }
*/


    /**
    * Buttons for fun!
    */

    if (joystick.joy1_Buttons & lBumper)
    {
			PlaySoundFile("whoops.rso");
    }



    /**
    * Button to change driving modes
    */

   	if(joystick.joy1_Buttons & startButton){
   		if(startPressed){
   			startPressed = false;
   			kMaximumPowerLevel = fast;
				PlaySound(soundBlip);
			}
			else{
				startPressed = true;
   			kMaximumPowerLevel = slow;
				PlaySound(soundBeepBeep);
			}
			wait1Msec(200);
			ClearSounds();
		}


		if(false){
		//Sensor Avoid
		if( SensorValue[rightSonar] > distance_in_cm ){
			motor[frontLeft]  = -1*autoSpeed;
    	motor[backLeft]   = autoSpeed;
			motor[frontRight] = autoSpeed;
    	motor[backRight]  = -1*autoSpeed;
			wait1Msec(500);
		}
		else if( SensorValue[leftSonar] > distance_in_cm ){
			motor[frontLeft]  = autoSpeed;
    	motor[backLeft]   = -1*autoSpeed;
			motor[frontRight] = -1*autoSpeed;
    	motor[backRight]  = autoSpeed;
			wait1Msec(500);
		}
	}



	/*
	*  Drive Train!
	*
	*/

	int powY1;
	int powX1;
	int powX2;
	powY1 = scaleJoystick(joystick.joy1_y1);
	powX1 = scaleJoystick(joystick.joy1_x1);
	powX2 = scaleJoystick(joystick.joy1_x2);

	if( abs(powY1) > 2 && abs(powX1) <= driveTrsh )
	{
	  // Straight drive, front to bCK
    motor[frontLeft]  = powY1;
    motor[backLeft]   = powY1;
		motor[frontRight] = powY1;
    motor[backRight]  = powY1;
  }
  else if( abs(powX1) > 2 )
  {
    motor[frontLeft]  = powX1*-1;
    motor[backLeft]   = powX1;
		motor[frontRight] = powX1;
    motor[backRight]  = powX1*-1;
	}
	else{
  	// Spin from side to side
  	motor[frontLeft]  = powX2*-1;
    motor[backLeft]   = powX2*-1;
		motor[frontRight] = powX2;
    motor[backRight]  = powX2;
	}

	wait1Msec(50); // avoid competing commands
	} //End While(main)
}
