#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Servo Control by NXT Motor -                                      *|
|*                                        ROBOTC on NXT + TETRIX                                          *|
|*                                                                                                        *|
|*  This program simply sweeps the servo back and forth.  Servo Change Rate can be changed by changing    *|
|*  'delta'.  (0 = max servo speed, # > 0 = how many servo positions to move per update (every 20ms).     *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  Be sure to attach a servo somewhere on the robot.                                               *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 1                  none                TETRIX Controller   TETRIX                              *|
|*    Port 1 - Chan. 1        servo1              std. Servo          The servo that you wish to test.    *|
\*---------------------------------------------------------------------------------------------------4246-*/
#include "JoystickDriver.c"

task main()
{

int delta = 2;                        // Create int 'delta' to the be Servo Change Rate.

  while(true)
  {
  	getJoystickSettings(joystick);
    servoChangeRate[srvo_S1_C2_6] = delta;          // Slow the Servo Change Rate down to only 'delta' positions per update.



    if(joy1Btn(4)==1)
    {
      while(ServoValue[srvo_S1_C2_6] < 255)
      {
        servo[srvo_S1_C2_6] = 255;                              // Move servo1 to position to 255.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.

    if(joy1Btn(5)==1)             // If servo1 is closer to 255 (than 0):
    {
      while(ServoValue[srvo_S1_C2_6] > 0)
      {
        servo[srvo_S1_C2_6] = 0;                                // Move servo1 to position to 0.
      }
    }

    wait1Msec(1000);                          // Wait 1 second.
  }
}
