#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     IRSeeker,       sensorI2CMuxController)
#pragma config(Motor,  motorA,          gripMotor,     tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          wristMotor,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     ramp,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Extend_Arm,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();
  int threshold = 5;             /* Int 'threshold' will allow us to ignore low       */
  servoChangeRate[srvo_S1_C2_5] = 3;

  waitForStart();   // wait for start of tele-op phase

  while (true)
  {
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.
      getJoystickSettings(joystick);
    if(abs(joystick.joy2_y2) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[mtr_S1_C1_1] = joystick.joy2_y2/2;         // Motor B is assigned a power level equal to the right analog stick's Y-axis reading.
    }
    else                                    // Else if the readings are within the threshold:
    {
      motor[mtr_S1_C1_1] = 0;                        // Motor B is stopped with a power level of 0.
    }


    if(abs(joystick.joy2_y1) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
    {
      motor[mtr_S1_C1_2] = joystick.joy2_y1/2;         // Motor C is assigned a power level equal to the left analog stick's Y-axis reading.
    }
    else                                   // Else if the readings are within the threshold:
    {
    motor[mtr_S1_C1_2] = 0;      																																																																																																															                  // Motor C is stopped with a power level of 0.
    }



		if(joy1Btn(6))                          //Button 6 moves servo to 175
		{
			{
        servo[srvo_S1_C2_6] = 175;
			}
		}
		else if(joy1Btn(5))                     //Button 5 moves servo to 10
		{
      {
        servo[srvo_S1_C2_6] = 10 ;
			}
		}
		else if(joy1Btn(4))                    //Button 4 moves servo to 80
		{
			{
				servo[srvo_S1_C2_6] = 80;
			}
		}


		if(joy1Btn(7)){motor[ramp]=10;}               // Button 7 ramp up 10
		else if(joy1Btn(8)){motor[ramp]=-20;}         // Button 8 ramp down 20
		else{motor[ramp]=0;}

		if(joy1Btn(1)){motor[Extend_Arm]=25;}          // Button 1 arm up at 25
		else if(joy1Btn(2)){motor[Extend_Arm]=-15;}    // Button 2 arm down at 15
		else
		{
			motor[Extend_Arm]=0;
		}



  }
}
